### ISSUE TITLE
LinkHints gets a wrong view area if page is zoomed on Chrome for macOS

### ISSUE THREAD

**Issue by agzam** [gdh1995/vimium-c#119] opened 2020-02-02 22:30 UTC
It's missing urls sometimes. 
Here's for example of a GitHub page, when `f` pressed, you can clearly see that all wiki links are ignored.

<img width="1621" alt="Screen Shot 2020-02-02 at 2 27 54 PM" src="https://user-images.githubusercontent.com/1091022/73616439-40bb1680-45c8-11ea-9ad4-426f90778764.png">

Just in case I checked if the same thing is also broken in Vimium and it is not. Vimium still recognized all links on the page

**upd:** Apparently when content zoomed-in to the point when `devicePixelRatio` exceeds `2`, link hinting breaks.

**upd 2:** This turned out to be specific to OS X and the way how it handles scaling. I failed to reproduce the issue on any other display, it only appears on the Macbook's internal retina display with scaled resolution.

**Comment by agzam** [comment] 2020-02-02 22:45
It's even more strange that the number of missed links do vary from a browser to browser - the screenshot above is from Brave. I tried the same thing, with the same page in Chrome - it still missing links, but not as many as in Brave.

**Comment by Monirzadeh** [comment] 2020-02-02 22:47
just for test
press `F2` in hint mode makes any different?

**Comment by agzam** [comment] 2020-02-02 22:52
it's the same - incognito in Chrome, private in Brave, still missing the links. `F2` has no effect whatsoever, what that suppose to do?

**Comment by agzam** [comment] 2020-02-02 22:55
Here's another screenshot
![image](https://user-images.githubusercontent.com/1091022/73616735-0e131d00-45cc-11ea-96f6-6c019c2ae4c1.png)

**Comment by Monirzadeh** [comment] 2020-02-02 22:57
> it's the same - incognito in Chrome, private in Brave, still missing the links. `F2` has no effect whatsoever, what that suppose to do?

i just test that for similar situation [here](https://github.com/gdh1995/vimium-c/issues/103)

**Comment by agzam** [comment] 2020-02-02 23:05
Okay, so I tried pressing `f` then scroll a bit, then `F2` -  some links get recognized, but again - not all. The workaround suggested in the linked issue unfortunatley is not a solution.

This bug pretty much makes this extension unusable outside of Firefox. I see that the reason how this feature is implemented differently from Vimium (classic) is for performance reasons. Maybe there's a flag that can be tweaked? I'd rather have all visible links on the page to be hinted, even if it slightly makes it slow.

**Comment by Monirzadeh** [comment] 2020-02-02 23:27
i test same page in brave (Vimium wiki) and it's work for me without any problem so i think something interrupt the extension
this is my scattershot on brave and Vimium C 1.80.1 on linux
![Screanshot-2020-02-03-02-44-24-389452987](https://user-images.githubusercontent.com/25131576/73617079-4ea48200-4630-11ea-972e-66b7fdf67dd4.png)

**Comment by gdh1995** [comment] 2020-02-02 23:55
I've applied some aggressive rules to exclude some of useless hints and add some other exact ones. Uh, so maybe that's a regression bug compared with an old version.


I will do some tests in this week. But from today my annual holiday has ended，so the development of Vimium C will slow down.



---Original---

**Comment by agzam** [comment] 2020-02-03 00:09
> so the development of Vimium C will slow down

Thank you for the heads up. Of course, take your time. No pressure. Those of us who made the switch from Vimium do appreciate the amazing work you've done and improvements you've made. Thank you very much!

**Comment by gdh1995** [comment] 2020-02-03 01:29
Hello, I didn't see the snapshot when I replied through email. According to these snapshot, it should be because Vimium C gets a wrong "visual viewport" (visible area).

So what's your screen DPI, browser and its version code, opearting system and its version ? Thanks for this report.

**Comment by agzam** [comment] 2020-02-03 02:13
Display resolution is set to 1680x1050. `screen` in DevTools reports the following:
```
Screen {availWidth: 1680, availHeight: 1027, width: 1680, height: 1050, colorDepth: 24, …}
availWidth: 1680
availHeight: 1027
width: 1680
height: 1050
colorDepth: 24
pixelDepth: 24
availLeft: 0
availTop: 23
orientation: ScreenOrientation
angle: 0
type: "landscape-primary"
onchange: null
__proto__: ScreenOrientation
__proto__: Screen
```
This behavior shows in Brave and Chrome, but not in Firefox.

**Comment by gdh1995** [comment] 2020-02-03 02:17
What's the result of `visualViewport` and `devicePixelRatio`?

**Comment by agzam** [comment] 2020-02-03 02:19
```
VisualViewport {offsetLeft: 0, offsetTop: 0, pageLeft: 0, pageTop: 4096.7998046875, width: 754.4000244140625, …}
offsetLeft: 0
offsetTop: 0
pageLeft: 0
pageTop: 4096.7998046875
width: 754.4000244140625
height: 760.7999877929688
scale: 1
onresize: null
onscroll: null
__proto__: VisualViewport
```
```
devicePixelRatio
2.5
```

**Comment by agzam** [comment] 2020-02-03 02:19
I tried changing display resolution to be smaller, but that didn't fix it.

**Comment by agzam** [comment] 2020-02-03 02:36
I tested it with my external monitor on 2560x1440 resolution and devicePixelRatio=1.25. And guess what? Everything looks fine. 

![image](https://user-images.githubusercontent.com/1091022/73621429-e7b0aa00-45ea-11ea-944e-d4ad08e9f71b.png)

So it's basically breaking on the internal screen of my 13'' Macbook. I'm gonna try testing it on my XPS 13 Linux Laptop sometime later.

**Comment by gdh1995** [comment] 2020-02-03 02:38
Is the size of your Chrome window maximized?

On my computer, `visualViewport.width` is near to `innerWidth` (their delta means a scrollbar), and `innerWidth * devicePixelRatio` is approximate to the width of screen resolution.

So could you provide info of `screen`, `innerWidth`, `innerHeight`, `visualViewport` of a tab in a maximized Chrome window (the Developer Tools should in a seperate window)?

**Comment by agzam** [comment] 2020-02-03 02:45
I've tried resizing browser window on both screens - where it fails, no matter how I change it, it stays broken. When it works - it works, no matter the size of the viewport. So it must be something to do with `devicePixelRatio`.

**Comment by agzam** [comment] 2020-02-03 03:23
it looks good on XPS 13, Linux with devicePixelRatio=2

**Comment by agzam** [comment] 2020-02-03 03:29
These are the parameters of the screen where it fails on hackernews

![image](https://user-images.githubusercontent.com/1091022/73623574-39a8fe00-45f2-11ea-9493-c55e199b1331.png)

**Comment by agzam** [comment] 2020-02-03 03:37
whoa, I didn't know, devicePixelRatio can be different on different sites? for some reason on Hackernews it's reporting 3, on GitHub 2.5. Is that, normal?

**Comment by gdh1995** [comment] 2020-02-03 03:39
Have you zoomed-out on github.com by <kbd>Command+-</kbd>?

**Comment by agzam** [comment] 2020-02-03 03:43
so, that's the actual bug I guess - on the default zoom-level where devicePixelratio is < 2, hinting is fine. When zoom levels exceed devicePixelratio of 2 - hinting breaks.

**Comment by agzam** [comment] 2020-02-03 03:46
I guess it's really not such a major issue that I initially thought it is. But it is still a bug.

**Comment by gdh1995** [comment] 2020-02-03 04:06
[vimium_c-1.80.1-dist-no-visualviewport.zip](https://github.com/gdh1995/vimium-c/files/4146216/vimium_c-1.80.1-dist-no-visualviewport.zip)

What about this version? I removed `visualViewport` from LinkHints.

**Comment by agzam** [comment] 2020-02-03 06:23
Ouch, I don't think it fixed it. I think it actually made it maybe worse? What I did is - I downloaded it, unzipped, loaded unpacked, (browser says it's unpacked), but now when zoomed-in, it hints even fewer links than before.

**Comment by agzam** [comment] 2020-02-03 06:28
This bug is so strange. I swear, I thought devicePixelRatio has something to do with it, but now I'm failing to replicate it on my external monitor (I went back to the Webstore version of the extension). No matter how much I zoom-in - it works. But on Macbook's screen even with just a bit of zooming - it doesn't hint bunch of links.

**Comment by gdh1995** [comment] 2020-02-03 06:30
What it will be if zoom-out and make `devicePixelRatio` be `1` on a page's web console, on your Mac's bulitin monitor?

**Comment by agzam** [comment] 2020-02-03 06:35
Here's how it looks. I connected external monitor and I still have my laptop open. When browser is on the external monitor:

zoom 200%, devicePixelRatio 2, all visible links are hinted:

![image](https://user-images.githubusercontent.com/1091022/73630737-d3c97000-460b-11ea-9ee0-37f00f316b3f.png)

now, moving browser to the laptop screen:

![image](https://user-images.githubusercontent.com/1091022/73630834-1b4ffc00-460c-11ea-9770-f224ca85fa9f.png)

Same browser, same zoom, devicePixelRatio reported 4

**Comment by agzam** [comment] 2020-02-03 06:37
I'm even trying to zoom on my external monitor so its devicePixelRatio goes above 3 and it still hints all visible links.

**Comment by gdh1995** [comment] 2020-02-03 06:37
Have you tested a case when your external monitor was disconnected?

**Comment by agzam** [comment] 2020-02-03 06:39
Yes, I can reproduce the bug on Macbook's display with good consistency.

**Comment by agzam** [comment] 2020-02-03 06:42
Here, I recorded a gif, so you can see how zooming affects the hints.

![zoom](https://user-images.githubusercontent.com/1091022/73631171-20fa1180-460d-11ea-9619-5cd961dec88a.gif)

**Comment by gdh1995** [comment] 2020-02-03 06:46
`[+getComputedStyle(document.documentElement).zoom, devicePixelRatio]` when zoom in/out?

**Comment by agzam** [comment] 2020-02-03 06:50
Initially, when zoom is 100%, that returns:
```
[+getComputedStyle(document.documentElement).zoom, devicePixelRatio]
(2) [1, 2]0: 11: 2length: 2__proto__: Array(0)
```

When I zoom-in to 125%, and that's when hints start breaking:
```
[+getComputedStyle(document.documentElement).zoom, devicePixelRatio]
(2) [1.25, 2.5]
```

When it's on 150%, and the hints are totally wacky:
```
[+getComputedStyle(document.documentElement).zoom, devicePixelRatio]
(2) [1.5, 3]
```

**Comment by agzam** [comment] 2020-02-03 07:00
Holy shit. This is what I did:

![image](https://user-images.githubusercontent.com/1091022/73632006-661f4300-460f-11ea-9498-88c4e782de7e.png)

And it now works fine. It's a scaling problem with OSX and Chromium I guess. 
I am very sorry for causing you so much trouble with this. It's probably better if fixed, but I guess it's not such a big deal. I'm not sure though how exactly Vimium (classic) handles this.

**Comment by gdh1995** [comment] 2020-02-03 07:02
Oops, then this issue is because of one of my tricks to support the `zoom` CSS style on `document.documentElement`:
* on my Win 10, there's a period that `document.documentElement`'s `zoom` keeps the same as `devicePixelRatio`, if only there're no CSS styles setting it.
* but this "feature" (or Chrome bug?) is not reproduced on Chrome 79, my Win 10...
* then Vimium C tends to think "**there's a zoom from page styles**" since `getComputedStyle(document.documentElement).zoom` returns a different value, so it crops some right and bottom hints.

I'll fix it in days. Thanks for your patience and tests.

**Comment by agzam** [comment] 2020-02-03 07:10
Ah, okay. Yeah, feel free to ping me anytime if you want me to run another test. It would suck if OSX users with Chromium browsers decide not to use the extension because of this bug. Thank you for your help.

**Comment by gdh1995** [comment] 2020-02-03 08:24
Um, I want to know what's `+[getComputedStyle(document.documentElement).zoom, devicePixelRatio]` when the page is not zoomd (aka. zoom level = 100%) by Chrome:
* on the built-in monitor, and not "open in low resolution"
* on the external monitor, and not "open in low resolution"
* on the built-in monitor, and enable "open in low resolution"
* on the external monitor, and enable "open in low resolution".

**Comment by gdh1995** [comment] 2020-02-03 12:41
As far as I've got, the wrong result occurs when:
1. enable the "open in low resolution" checkbox
2. open Chrome on the bulit-in monitor
- 1. then `getComputedStyle(document.documentElement).zoom` will return the **browser-level zoom ratio**, while is not equal with JavaScript's `window.devicePixelRatio` (which should be physical DPI * browser-level zoom).
3. if zoom-in a page and make its browser-level zoom ratio larger than 1 (like 110%, 125%, 150%...),
- 1. then `getComputedStyle(document.documentElement).zoom` will return 1.1 / 1.25 / 1.5 / ...

Are these right? If they're, then there seems no good way to detect such a bug, and maybe a new option is necessary to manually work it around (let you tell Vimium C what's the basic DPI).

**Comment by agzam** [comment] 2020-02-04 19:21
I'm not following you, with "open in low resolution" I can no longer reproduce the bug. Only when the checkbox is "off" I can reproduce it, and only on the Macbooks internal display. Maybe it's really not worth wasting time trying to fix it?

**Comment by gdh1995** [comment] 2020-02-05 00:31
so, the zoom is not equal with DPI when the 'open in low resolution' unchecked? when you checked it, are the two values keeping the same?
I've found a Chrome's runtime flag of "enable-zoom-***-dsf" and it causes the same buggy behavior on Win 10, if just disable it.
So, I have decided to fix it, by&nbsp;adding an extra step before linkhints really executes. Vimium C can access the real zoom radio using an extension API, but I once think it takes more time so haven't adopted it.



---Original---

**Comment by gdh1995** [comment] 2020-02-05 12:50
So please try this - I've marked most `getComputedStyle(documentElement).zoom` untrusted - then it should work when you uncheck the "low resolution" box.

[vimium_c-1.80.1-chrome-6ec887c.zip](https://github.com/gdh1995/vimium-c/files/4159526/vimium_c-1.80.1-chrome-6ec887c.zip)

**Comment by agzam** [comment] 2020-02-12 01:09
Tried that. "Open in low resolution" *is unchecked*. You have fixed it! Thank you very much! 

![chromium-c](https://user-images.githubusercontent.com/1091022/74293920-216f6800-4cf1-11ea-8caa-b91806f861ba.gif)

**Comment by gdh1995** [comment] 2020-02-12 01:35
OK.

The v1.80.2 is being published to Chrome Web Store (waiting for verifying). However it can not support zoom changes - only the first page-zoom value will be recognized, because of a typo. This will be fixed in a next version of Vimium C.

**Comment by gdh1995** [comment] 2020-02-24 03:20
v1.80.3 has been published, and it supports: 1. show Link Hints and hide; 2. change page zoom level; 3. show LinkHint again.

**Closed by gdh1995** 2020-02-24 03:20 UTC
