### ISSUE TITLE
go to input select all text on that

### ISSUE THREAD

**Issue by Monirzadeh** [gdh1995/vimium-c#87] opened 2019-11-11 13:52 UTC
hi
when i  search something than in google than pres i
`map i focusInput`
that select all text in search box instead of go to end of text
it happen only in google other sites work -youtube, reddit, etc... - fine ( pres i go end of text in input box)

**Comment by gdh1995** [comment] 2019-11-11 15:55
On my computer, `i` will also move caret to the end of query text on Google search result pages. And according to the code, `focusInput` has a parameter of `select=""/all/all-line/start/end`, and its default value is just "end". So I think it may be because some other JavaScripts code (from the page or other extensions) did such selecting actions.

Could you test the behavior of `focusInput` with a new blank profile for Chrome / Firefox?

**Comment by Monirzadeh** [comment] 2019-11-11 16:33
i test with a new profile without any extension (default Firefox profile) 
issue happen again
i use Ubuntu 19.10 with bspwm
is this command correct?
`map i focusInput select="end"`

**Comment by gdh1995** [comment] 2019-11-11 22:30
The `map` is correct. Then, does this issue exist on GNOME/KDE? What's your version&source of Firefox, installed from `apt-get` or downloaded by yourself?

I'll run a VM to test this on Ubuntu in a few days.

**Comment by Monirzadeh** [comment] 2019-11-11 22:36
i use Mozilla Firefox 70.0.1 that install with apt from official repository
i test on KDE and report that here as soon as possible
problem happen on google and not on other site (until now)

**Comment by gdh1995** [comment] 2019-11-11 22:43
It's so unexpected that I just reproduced this issue on Firefox + Win10, but never on Chrome+Win10. Maybe some inner code of Vimium C is not so compatible, I'll fix it when I find where.

**Comment by Monirzadeh** [comment] 2019-11-13 09:55
i test that on firefox in KDE. the same issue happen there

**Comment by gdh1995** [comment] 2019-11-13 10:13
Um, I think I've found the root cause, but in my plan I will release a new version in at least one week. So please test this ZIP file: [vimium_c-1.78.6-fx.zip](https://github.com/gdh1995/vimium-c/files/3840535/vimium_c-1.78.6-fx.zip) by loading it on `about:debugging`.

**Comment by Monirzadeh** [comment] 2019-11-13 10:18
i test that and it is fix the problem.
thanks for your fix.

**Comment by gdh1995** [comment] 2019-11-18 00:01
v1.78.7 has released, and now I close this issue. If this bug is still reproduced, feel free to reopen it.

**Closed by gdh1995** 2019-11-18 00:01 UTC
