### ISSUE TITLE
Key 'f' doesn't work.

### ISSUE THREAD

**Issue by mongemalo** [gdh1995/vimium-c#77] opened 2019-10-06 00:50 UTC

**Comment by gdh1995** [comment] 2019-10-06 02:01
Thanks for this report. This bug only occurs on Vimium C v1.78.0 on Firefox, and v1.78.1 has been released and published to fix it. Please have a try.

**Comment by n4n0GH** [comment] 2019-10-08 19:51
Sometimes it might not work directly after Vimium C has been installed. Terminating the browser process completely and restarting Firefox makes `f` work like expected.

**Comment by gdh1995** [comment] 2019-10-09 02:09
@n4n0GH Could you provide your current versions of Vimium C and Firefox, and some page URLs having this problem?

**Comment by n4n0GH** [comment] 2019-10-09 13:11
Well for me it was on the following setup:
Firefox 69.0.1
Vimium C 1.78.1
But like I said, a restart of the browser was all it needed to get the key to work like expected.

**Comment by gdh1995** [comment] 2019-10-09 14:05
Normally, Vimium C works on all pages "at once" you install it, so it's strange for me that you need to restart it.

Well, now that it's not very important, I'll close this issue since it has been solved. If the case of restarting are reproduced on my computers, I'll add a comment here.

**Closed by gdh1995** 2019-10-09 14:05 UTC
