### ISSUE TITLE
gnw设置成打开页面的快捷键就不行,其他都可以,很奇怪

### ISSUE THREAD

**Issue by avatar70t** [gdh1995/vimium-c#954] opened 2023-06-11 01:28 UTC
map gnw openUrl url="https://www.youtube.com/"

**Comment by gdh1995** [comment] 2023-06-11 16:05
Sorry it's a bug imported on 2022/10/31. I'll fix it soon.

Duplicate of https://github.com/gdh1995/vimium-c/issues/954 .

**Comment by gdh1995** [comment] 2023-06-15 15:15
Hello a new version has been released and you may take a try.

**Comment by avatar70t** [comment] 2023-06-19 16:02
great!perfect

**Closed** 2023-06-24 14:28 UTC
Labels: bug, duplicate
