### ISSUE TITLE
mapKey command no longer working Chrome Version 90.0.4430.212 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by stron-jay** [gdh1995/vimium-c#355] opened 2021-05-27 23:58 UTC
I've never had any trouble with this command since I started using Vimium back in December.

`mapKey Z <esc>` and example on side `mapKey <c-s-e> <esc>` produces
`Error: Unknown mapping command: "mapKey" in mapKey Z <esc>`.

**Comment by stron-jay** [comment] 2021-05-28 00:06
`mapkey Z <esc>` does work. There may have been some work done that does not differentiate between lowercase and uppercase alpha character values. It would be beneficial for the example commands linked to the right to be updated to `mapkey <c-s-e> <esc>`

**Comment by gdh1995** [comment] 2021-05-28 01:06
&nbsp;Oh, yes, the lowercase works.&nbsp; This issue is because of a typo bug.



---Original---
From: "Jay ***@***.***&gt;
Date: Fri, May 28, 2021 08:06 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] mapKey command no longer working Chrome Version 90.0.4430.212 (Official Build) (64-bit) (#355)




 
mapkey Z <esc&gt; does work. There may have been some work done that does not differentiate between lowercase and uppercase alpha character values. It would be beneficial for the example commands linked to the right to be updated to mapkey <c-s-e&gt; <esc&gt;

**Comment by gttotev** [comment] 2021-05-29 02:46
On a related note, I can verify `mapkey Z <esc>` works for me too, but `mapkey <s-esc> <esc>` no longer seems to work, while it did before the update a few days ago.

**Comment by gdh1995** [comment] 2021-05-29 10:33
Some browser-level shortcuts can not be blocked by Vimium C, which is a limitation of browsers like Chrome and Firefox, and `Shift+Escape` will be handled by Chrome to open its built-in "task manager":

![image](https://user-images.githubusercontent.com/5547703/120067086-4afdff80-c0ac-11eb-9047-5f9453a76461.png)

**Comment by gttotev** [comment] 2021-05-29 23:17
But this doesn't explain why I could use `Shift+Escape` before `v1.9.0` to activate `<esc>`.

**Comment by gdh1995** [comment] 2021-05-30 02:58
@gttotev  Are you using macOS or Linux ? Maybe detailed info about your platform will help.

And here's an archive of Vimium C v1.89.1 (Chrome-only version): [vimium_c-1.89.1-chrome.zip](https://github.com/gdh1995/vimium-c/files/6565635/vimium_c-1.89.1-chrome.zip) , and could you do some tests with it on your computer ? (Here's the usage of .zip file: https://github.com/gdh1995/vimium-c/wiki/Test-a-zip-package )

**Comment by gdh1995** [comment] 2021-05-30 03:02
Oh sorry @gttotev , I just reproduced it.

**Comment by gttotev** [comment] 2021-05-31 20:50
No problem @gdh1995, here's my system info FYI (to help in debugging):
```
Chromium: 90.0.4430.212 (Official Build) (x86_64)
OS: macOS Version 10.14.6 (Build 18G9028)
JavaScript: V8 9.0.257.29
```
I tested `v1.89.1` and can confirm `<s-esc>` properly mapped to `<esc>` for me too in that version.

**Comment by gdh1995** [comment] 2021-06-01 01:05
&nbsp;I have found why and fixed it. A new version will be released in this week.



---Original---
From: "Gabriel ***@***.***&gt;
Date: Tue, Jun 1, 2021 04:50 AM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] mapKey command no longer working Chrome Version 90.0.4430.212 (Official Build) (64-bit) (#355)




 
No problem @gdh1995, here's my system info FYI (to help in debugging):
 Chromium: 90.0.4430.212 (Official Build) (x86_64) OS: macOS Version 10.14.6 (Build 18G9028) JavaScript: V8 9.0.257.29  
I tested v1.89.1 and can confirm <s-esc&gt; properly mapped to <esc&gt; for me too in that version.

**Comment by gdh1995** [comment] 2021-06-04 06:34
V1.90.2 has been available on Firefox and Chrome stores, and you may take a try.

**Comment by gttotev** [comment] 2021-06-04 18:28
Works now, thanks for the support @gdh1995!

**Closed** 2021-06-05 02:02 UTC
Labels: bug
