### ISSUE TITLE
Vimium-C just being present breaks ProtonMail web client

### ISSUE THREAD

**Issue by ndom91** [gdh1995/vimium-c#800] opened 2022-11-12 11:19 UTC
**Describe the bug**

Vimium-C simply being enabled in the browser seems to break some functionality in the Proton mail client. For example, I cannot use the keyboard shortcuts when certain areas of the page are focused, but I can when other areas are focused. 

In addition, expanding quoted emails in an email thread does not work at all. The button behaves as if disabled.

I've disabled all shortcuts for vimium-c, however, while the extension is enabled at all in the browser, it still seems to be breaking some functionality.

![image](https://user-images.githubusercontent.com/7415984/201471590-b2cbe11c-0998-4653-b8d9-32f5c5cc7967.png)

Any idea what could be going on here? Is there a way to more significantly disable vimium-c for certain domains / tabs without disabling it completely in the extension manager?

**To Reproduce**

0. Install vimium-c and disable all shortcuts for the `mail.proton.me` domain
1. Sign in to `mail.proton.me`
2. Open an Email
3. Focus the email body
4. Observe that the `t` keybaord shortcut to Trash the current email **does not** work
5. Focus the email toolbar or any of the other global UI elements
6. Observe that the `t` keyboard shortcut to Trash the current email **does work**

Go to `brave://extensions` and disable Vimium-C

1. Open an email in `mail.proton.me` 
2. Focus the email body
3. Observe that the `t` Trash keyboard shortcut now works

In addition, this type of "Expand Quoted Emails" button do not work either while vimium-c extension is enabled in the browser.

![image](https://user-images.githubusercontent.com/7415984/201471752-6c52a837-0abb-42e8-9b0a-0b39939f47ed.png)

**Browser, OS and Vimium C versions**

- Browser name: Brave 
- Browser version: 1.43.89 Chromium: 105.0.5195.102 (Official Build) (64-bit) 
- Vimium C version: 1.99.5
- OS name and version: Arch Linux 5.19.3

**Comment by gdh1995** [comment] 2022-11-14 16:45
Confirmed and its shortcuts like `t` will be fixed in v1.99.8.

Because of some tech limitations, if a new mail shows its content, then Vimium C can not receive keyboard events on it, so key mappings won't work. When you meet this (in v1.99.8), you may click the top / left blank area and press `f` to activate `LinkHints`, and `LinkHints` will do some checks and fix the problem, so that Vimium C's mappings will work again on the mail content area. But this fix only works till another mail content replaces it.

I've added some tricks to solve the failure problem, but there's no completely reliable way to fix it. So, if you meet it or worry about it, you may frequently press `f` if only you think it may help - it seems `f` in ProtonMail's shortcuts is harmless.

**Comment by gdh1995** [comment] 2022-11-14 18:31
Um, I didn't made such a "quoted mail", so it's not tested yet. Could you give a snapshot to show where it is, or send such a mail to my account (gongdh11@proton.me) ? Then I can test it.

I only found this:
![image](https://user-images.githubusercontent.com/5547703/201738343-ba3ec13e-6851-4b56-bb2e-6ae243f7dc4a.png)

**Comment by ndom91** [comment] 2022-11-14 18:52
> 

Yeah thats exaclty what I meant - as shown in the screenshot in my previous post, where I blocked a bunch of stuff out in red.

Is that working for you? Wasn't for me :thinking:

**Comment by gdh1995** [comment] 2022-11-14 20:40
Oh I reproduced a broken `show original message` with v1.99.5. It has a same root cause with the missing webpage shortcuts like `t`, and may be fixed in v1.99.8 (though not in v1.99.7).

**Comment by gdh1995** [comment] 2022-11-23 06:18
Hello, v1.99.90 has been released on Chrome Web Store, and you may take a try.

**Closed** 2022-11-24 09:57 UTC
Labels: bug
