### ISSUE TITLE
Firefox: pressing 't' does not open new tab

### ISSUE THREAD

**Issue by sluongng** [gdh1995/vimium-c#51] opened 2019-06-24 11:58 UTC
# Version tested

- 1.75.7 Firefox Nightly
- 1.75.7 Vimium-c Chrome stable

# What did you do

- Open browser
- Open `google.com`
- Press 't' to open new tab

# Expected result

- Browser open a new tab

# Actual result

- Firefox does not open new tab
- Chrome does open a new tab

# Note

- Every other features are still working normally on firefox (o, b, j, k, f, ...)

- CMD + t still work as hotkey to open new tab

**Comment by gdh1995** [comment] 2019-06-24 12:02
Are you downloading Vimium C from Chrome Web Store or Firefox Add-ons?


 
---Original---

**Comment by gdh1995** [comment] 2019-06-24 12:16
Tested with Vimium C master (BTypes = Firefox) on Firefox 69.0a1 (64-bit, Win 10), I can not reproduce it.

What's your settings of "New tab URL"? Maybe recent Firefox disables more URLs - as far as I know, Vimium C can not create a tab of `file:///` or `about:debugging`.

Reference of `browser.tabs.create`: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create , the `url` sub-section.

**Comment by sluongng** [comment] 2019-06-24 14:57
![image](https://user-images.githubusercontent.com/26684313/60029186-3ef4b080-96d3-11e9-99cd-a7c33b3ed819.png)

My Firefox Add-ons get automatically updated so I think it come from the store.

The above is what I get when i try to inspect into the extension.

**Comment by gdh1995** [comment] 2019-06-24 15:02
The reason that I asked the version of Vimium C is you said this in this issue: 

> * 1.75.7 Vimium-c Chrome stable

- Just in case you got a mismatched version.

> what I get when i try to inspect into the extension

A strange bug. I once tested those URLs and `about:newtab` should be OKay. Are you using another web-extension to override the Firefox's NewTab URL setting?

I'll do more tests on latest Firefox in days.

**Comment by gdh1995** [comment] 2019-06-24 19:08
Confirmed as a bug, and 7eabcc548ea539390d372b3cfd14f658a474534a should fix it. I'll publish a new version in days.

**Comment by gdh1995** [comment] 2019-06-25 18:51
v1.75.8 has been released on Firefox Add-ons. You may have a try.

**Comment by sluongng** [comment] 2019-06-26 14:29
I am on 1.75.8 right now and can confirm that I can use 't'

However when open a new tab (firefox) with 't' or Cmd + T, the url bar is filled instead of being empty
- "moz-extension://9a678822-07c0-d04a-bff7-cb09a8e380da/pages/blank.html" when leave at default configuration
- "about:blank" when try to force save "about:blank" (and yes, this works for Firefox Nightly for some reason despite the warning message of Vimium when you save the Options page

**Comment by gdh1995** [comment] 2019-06-26 14:37
Um... You're right, `about:blank` is not forbidden by Firefox.

But, the fact is that Firefox has "too strict" limitation on URLs that web-extensions want to open, and `about:home` is indeed forbidden on Firefox 67.

The URL in address bar is because:
* up to now, Vimium C declares that its "new tab page" is "<ext-origin>/pages/newtab.html"
* if the newtab.html is opened, it will load the value of Vimium C's "New Tab URL" option and try to open it.
  * there's no way to read a browser's previous New Tab page settings.
  * a side effect of this "trying to open" is the target URL is shown on the address bar.

There have been so many discussions and complaints about Vimium C's behavior of overriding New Tab, so I've planned to split this feature into another web-extension (Some discussions in Chineses may be seen in https://github.com/gdh1995/vimium-c/issues/47). It will be in Vimium C v1.76.*** or v1.77.

**Comment by sluongng** [comment] 2019-06-26 16:36
Complain tickets on Extension limitation on URL bar for Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1409675

Possible solution (WIP) ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1460412

**Comment by meluskyc** [comment] 2019-09-13 23:32
@gdh1995 I am using 1.77.2 on Firefox and am still having this issue. I thought this might have been fixed in 1.77 since new tab is no longer being managed, but `t` is still not working for me. Is this possible to fix? Thanks.

**Comment by gdh1995** [comment] 2019-09-14 03:22
Some URLs are refused by Firefox to open from an extension. So what's your chosen NewTab on Vimium C Options page?

**Comment by meluskyc** [comment] 2019-09-14 04:22
It's the default about:newtab.

**Comment by gdh1995** [comment] 2019-09-14 12:27
@meluskyc Vimium C v1.77.3 has been released on Firefox Add-ons, and you may try it again.

**Comment by meluskyc** [comment] 2019-09-14 13:21
Fixed. Thank you!

**Closed** 2019-09-14 13:22 UTC
