### ISSUE TITLE
[BUG] Custom CSS can not reach elements inside #shadow-root

### ISSUE THREAD

**Issue by n4n0GH** [gdh1995/vimium-c#78] opened 2019-10-08 19:57 UTC
## Issue
While trying to style the HUD element of Vimium C, I found out it was impossible to target the elements within the shadow-root element. Specifically, trying to change the font-size of the HUD text becomes near impossible, unless I'm missing something.

## Steps to reproduce
1) Go to Vimium C settings' custom CSS editor
2) Create a new target for `#s` (the `/` character for the search) and fill with arguments (e.g. "color: red!important;")
3) Save changes and invoke search
4) As observable, the `/` character is not rendered in red color

**Comment by gdh1995** [comment] 2019-10-09 02:20
The custom CSS need to satisfy special formats: if you want to write CSS code for the Find HUD, then please prefix them with `/* #find */` . This means only this:

``` css
/* #find */
#s {color: red;}
#s {padding-left: 5px;}
```

works.

### Explanations

* Vimium C use the comments of `/* #find */` and `/* #omni */` to learn what parts of CSS rules are for what UI components.
* the Find HUD is inside a shadow root in a blank `<iframe>`, and the relevant CSS code are injected into a `<style>` inside the shadow root, so it does work.

### More

The Vimium C Options page has a feature of live preview, but now I find it has broken for days. As a result, you must save all options to see the effects.

This bug will be fixed in a next released version.

**Closed** 2019-10-09 13:20 UTC

**Comment by gdh1995** [comment] 2019-10-09 13:24
Any Wiki page is welcome. Fell free to do it ! (you may have to read the code to get all rare usages it supports)

**Comment by maxigaz** [comment] 2020-05-09 08:35
> (you may have to read the code to get all rare usages it supports)

@gdh1995 Could you give me some pointers on which part of the code should be used for reference? I'm especially curious if the appearance of the Options page can be customised.

Since I can’t find any wiki pages about using custom CSS, I can create one that explains at least the basics as a starting point.

**Comment by gdh1995** [comment] 2020-05-09 08:46
For the Vimium C Options page, its styles are in [pages/options.css](https://github.com/gdh1995/vimium-c/blob/master/pages/options.css).

Basic styles of UI elements are in [front/vimium-c.css](https://github.com/gdh1995/vimium-c/blob/master/front/vimium-c.css), and those for Vomnibar panel are in [front/vomnibar.html](https://github.com/gdh1995/vimium-c/blob/master/front/vomnibar.html).

The `Custom CSS for Vimium C UI` is only for UI elements of various commands, like LinkHints, HUD, Vomnibar and FindBar. You can use selectors in `front/vimium-c.css` to adjust styles.

**Comment by maxigaz** [comment] 2020-05-09 09:28
Thank you for the quick reply!

You mentioned in an earlier reply that `/* #omni */` and `/* #find */` are necessary to style the Vomnibar and Findbar, respectively. That was very helpful, and I could style both these elements in the Custom CSS section.

What about the HUD and LinkHints? I’ve looked at the .css and .html file you linked, but I can’t find anything like `/* #hud */`. Or shall I just put their rules under `/* #omni */`?

I’ve tried the following, and all of it works except styling the HUD (messages like entering visual/caret mode):

```diff
/* #omni */
#list { background: #2f343f; }
#bar { background: #404552; }
#input { background: #2f343f; }
a { color: #5d99e6; }
.button:hover { background: #20242c; }
.item { border-color: #404552; }
+ .HUD:after { background: #2f343f; }

/* #find */
.r.D { background: #2f343f; box-shadow: none; }

+ /* #hud */
+ .HUD:after { background: #2f343f; }
```

**Comment by gdh1995** [comment] 2020-05-09 09:33
All rules:
* before `/* #omni */` and `/* #find */` sections
* or after a `/* #ui */` header

are for "normal" (LinkHints, HUD, ...) elements. Currently the second one of `#ui` will replace the first one, but not be appended to it.

**Comment by gdh1995** [comment] 2020-05-09 09:36
Vomnibar has a special dark mode, which can be enabled even when system color scheme is `light`: add "` dark`" (notice the space at the begin) to the `styles` item of `Vomnibar settings`.

**Comment by maxigaz** [comment] 2020-05-09 10:04
> All rules:
> 
>     * before `/* #omni */` and `/* #find */` sections
> 
>     * or after a `/* #ui */` header
> 
> 
> are for "normal" (LinkHints, HUD, ...) elements. Currently the second one of `#ui` will replace the first one, but not be appended to it.

Do you mean one of the following?

```
.HUD:after { background: red; }

/* #omni */
...

/* #find */
...
```

```
/* #omni */
...

/* #find */
...

/* #ui */
.HUD:after { background: red; }
```

I’ve just tried both, and none of them seem to affect the HUD. (I’m using Firefox 75.0 with VImium C v1.83.1.)

**Comment by gdh1995** [comment] 2020-05-09 10:35
Just save options and refresh the page? the live previewing seems to have a new regression bug.

**Comment by maxigaz** [comment] 2020-05-09 11:02
> Just save options and refresh the page?

I’ve already tried that. After some additional testing, it turns out the actual cause is something else: having the option `Auto switch between light and dark mode` enabled (which turns dark mode on for me). If I disable it, the HUD is styled as expected.
