### ISSUE TITLE
goBack seems not working

### ISSUE THREAD

**Issue by ABackerNINI** [gdh1995/vimium-c#360] opened 2021-06-03 02:00 UTC
I removed all my key maps and the default goBack key "H" still not work. The goForward key "L" works well.
This problem appears after the update today.

Vimium C 1.90.0，MS Edge 91，Windows

BTW, this is really a good extension! ^_^

**Comment by gdh1995** [comment] 2021-06-03 02:25
This is indeed a bug. A duplicate of #353, which has been fixed in v1.90.1 on Firefox and Chrome. The edge version (v1.90.0) had been through a very long review by admins of MS Edge and just got updated yesterday.

A new version  of v1.90.2 is been reviewing again, and may be published in days (or 1~2 weeks).

**Comment by gdh1995** [comment] 2021-06-03 02:26
You may add a custom key mapping rule of `map H goBack $count=-1` to work around this bug.

**Comment by ABackerNINI** [comment] 2021-06-03 02:28
yes, it works now, nice! thanks.

**Comment by gdh1995** [comment] 2021-06-10 11:06
Hello, v1.90.2 has been published on MS Edge Add-ons.

**Closed** 2021-06-10 11:06 UTC
Labels: bug, duplicate
