### ISSUE TITLE
GitHub comment's `quote reply` does nothing on LinkHints

### ISSUE THREAD

**Issue by asklow** [gdh1995/vimium-c#804] opened 2022-11-15 08:58 UTC
**Describe the bug**
While using github's comment section, each comment has "menu" (3 dots). Under that, activating "quote reply" with vimium-c link hint doesn't actually quote the reply.

**Steps to reproduce the behavior:**
1.  Head to any github comment section
2. Access 3 dot menu of a comment
3. Activate "quote reply" via link hint
4. Compare it with mouse action

**Browser, OS and Vimium C versions**

- Browser name: Chromium
- Browser version: 107.0.5304.110
- Vimium C version: v1.99.5
- OS name and version: Arch Linux 6.0.8-zen1-1-zen

**Comment by gdh1995** [comment] 2022-11-15 09:16
Confirmed. A bit strange.

**Comment by gdh1995** [comment] 2022-11-22 13:32
Yes `LinkHints` can only "simulate" mouse events.

I reviewed code of GitHub webpages, and found:
1. GitHub checks `event.isTrusted` and ignore a click event if only: it's untrusted and there's no selected text
2. I guess it's to tell from mouse click and fake click events created by `replyButton.click()` during its built-in keyboard shortcut <kbd>R</kbd>

![image](https://user-images.githubusercontent.com/5547703/203326278-bd1cffe4-6694-422d-a6fb-d065cc694556.png)

**Comment by gdh1995** [comment] 2022-11-22 13:33
This can not be fixed by Vimium C -  but maybe you can file an issue to the GitHub team, though I don't know where and how.

**Comment by gdh1995** [comment] 2022-11-22 14:38
Sadly `isTrusted` is the only property of `XxxxEvent` which Vimium C can not simulate.

I find a interesting thing: we know usually a <kbd>Space</kbd> key on a `<button>` will click it, but the above code also disables this common usage. What about filing an issue about this point?

**Comment by gdh1995** [comment] 2022-11-22 14:59
Ah, I filed https://github.com/orgs/community/discussions/39761 .

**Comment by gdh1995** [comment] 2022-12-25 17:46
Closed because it's an external issue, although https://github.com/orgs/community/discussions/39761 has no new updates yet.

**Closed by gdh1995** 2022-12-25 17:46 UTC
Labels: question, wontfix:external, external

**Comment by gdh1995** [comment] 2022-12-25 19:05
Um, it's because I think there's nothing I can do to work around GitHub's code. If you do want to track the conflict here, please reopen this issue then.
